on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v4
      - name: Build container
        uses: ./.github/workflows/build-image.yml
        with:
          image_name: zinstack625/iscraweb-ttbot
        secrets:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN  }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to stable
        uses: grebois/kube-tools@v1.5.2
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        with:
          kubectl: 1.18.2
          command: |
            kubectl rollout restart -n iscraweb deployment ttbot
