on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to bleeding edge
        uses: grebois/kube-tools@v1.5.2
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
          NAMESPACE: ${{ secrets.NAMESPACE }}
          RESOURCE: ${{ secrets.RESOURCE }}
          RESOURCE_TYPE: ${{ secrets.RESOURCE_TYPE }}
        with:
          kubectl: 1.18.2
          command: |
            echo -n "$KUBECONFIG_FILE" > .kubeconfig
            export KUBECONFIG=$(pwd)/.kubeconfig
            kubectl rollout restart -n $NAMESPACE $RESOURCE_TYPE $RESOURCE
